[package]
name = "aero"
version = "0.1.0"
edition = "2024"

[dependencies]
colored = "3.1.1"
lexer = { path = "compiler/lexer" }
parser = { path = "compiler/parser" }
syntax = { path = "compiler/syntax" }
hir = { path = "compiler/hir" }
semantic = { path = "compiler/semantic" }
visualizer = { path = "compiler/visualizer" }

[workspace]
members = [
    "compiler/assembler",
    "compiler/syntax",
    "compiler/generator",
    "compiler/hir",
    "compiler/lexer",
    "compiler/parser",
    "compiler/semantic",
    "compiler/visualizer",
    "lsp",
]
